### ISSUE TITLE
Apply for render algorithm code

### ISSUE THREAD

**Issue by Choyaa** [tsattler/meshloc_release#7]
Hi Tsattler,

It is an impressive works. I see the render code in meshloc is not available anymore(https://arxiv.org/pdf/1601.06950.pdf), but its very important for my reaserch. I would very appriciate, if you could provide me the MeshLoc's render algorithm.  Or, there is another render engine/algorithms is avaliable (as you know). 

Thank you so much! Looking forward to your reply.

**Comment by tsattler** [comment]
Thank you very much for the kind words.

I am not sure what the legal status of the rendering code is given that the original repository is not available and it is not clear to me why the original code is not available anymore (I guess the lab stopped existing). I also don't have the time at the moment to investigate this. As such, I don't feel comfortable sharing the code.

There are other libraries that you can use for rendering, e.g., PyRender and Open3D. We experimented with both and they worked well for many models. However, they did not properly render very large models, which is why we switched to the other renderer. These problems might not exist anymore though.

**Comment by v-pnk** [comment]
Hi @Choyaa,

we had issues with rendering very large models in Open3D, which seem to be still present (see [this Open3D issue](https://github.com/isl-org/Open3D/issues/3307)), however it works for the models presented in our paper.

Note that I had to use Open3D 0.15, as I get a Segmentation fault in 0.16 (probably connected to [this issue](https://github.com/isl-org/Open3D/issues/4881)).
